[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dryes"
version = "3.2.5"
description = "A package to compute operational indicators for drought risk assessment, developed by CIMA Research Foundation"
authors = [
    { name = "Luca Trotter", email = "luca.trotter@cimafoundation.org" },
    { name = "Michel Isabellon"},
    { name = "Checco Avanzi"}
]
maintainers = [
    { name = "Luca Trotter", email = "luca.trotter@cimafoundation.org"}
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: ECPL License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy~=2.3.5",
    "xarray~=2025.11.0",
    "astropy~=7.2.0",
    "scipy~=1.16.3",
    "lmoments3~=1.0.8",
    "netCDF4~=1.7.3",
    "h5netcdf~=1.7.3",
    "d3tools@git+https://github.com/c-hydro/d3tools"
]

[project.urls]
Repository = "https://github.com/c-hydro/dryes"

[project.optional-dependencies]

# dependencies for creating thumbnails
thumbnails = [
    "d3tools[thumbnails]@git+https://github.com/c-hydro/d3tools"
]

# dependencies for reading and writing remote data
remote-data = [
    "d3tools[remote-data]@git+https://github.com/c-hydro/d3tools"
]